const actions = {
  POSTJOB : "POSTJOB",
  LISTJOB : "LISTJOB",
  STUDENTSEARCH : "STUDENTSEARCH",
  JOBSAPPLIED : "JOBSAPPLIED",
  POSTEVENT : "POSTEVENT",
  LISTEVENT : "LISTEVENT"
};

module.exports = actions;