const actions = {
  POSTJOB : "POSTJOB",
  LISTJOB : "LISTJOB",
  STUDENTSEARCH : "STUDENTSEARCH",
  JOBSAPPLIED : "JOBSAPPLIED",
  POSTEVENT : "POSTEVENT",
  LISTEVENT : "LISTEVENT",
  LISTMSGS : "LISTMSGS",
  POSTMSG : "POSTMSG",
  LISTREGISTEREDSTUDENT : "LISTREGISTEREDSTUDENT",
  REGISTERSTUDENTEVENTLIST : "REGISTERSTUDENTEVENTLIST",
  JOSBSAPPLIEDSTUDENT : "JOBSAPPLIEDSTUDENT",
  STUDENTAPPLIED : "STUDENTAPPLIED",
  UPDATEJOBSTATUS : "UPDATEJOBSTATUS",
  REGISTEREDSTUDENTLIST : "REGISTEREDSTUDENTLIST"
};

module.exports = actions;