export const FILL_STUDENT_DETAILS = "FILL_STUDENT_DETAILS";
export const FILL_EMPLOYER_DETAILS = "FILL_EMPLOYER_DETAILS";
export const FILL_BOTH_DETAILS =  "FILL_BOTH_DETAILS";
// export const FILL_OTHER_STUDENT_DETAILS = "FILL_OTHER_STUDENT_DETAILS";

export const FILL_STUDENT_BASIC_DETAILS = "FILL_STUDENT_BASIC_DETAILS";
export const FILL_STUDENT_EDUCATION_DETAILS = "FILL_STUDENT_EDUCATION_DETAILS";
export const FILL_STUDENT_EXPERIENCE_DETAILS = "FILL_STUDENT_EXPERIENCE_DETAILS";
export const FILL_STUDENT_IMAGE_DETAILS = "FILL_STUDENT_IMAGE_DETAILS";
export const FILL_STUDENT_RESUME_DETAILS = "FILL_STUDENT_RESUME_DETAILS";



export const FILL_JOB_DETAILS_LIST = "FILL_JOB_DETAILS_LIST";

export const FILL_EVENT_DETAILS_LIST = "FILL_EVENT_DETAILS_LIST";

export const FILL_MSG_DETAILS_LIST = "FILL_MSG_DETAILS_LIST";