export const FILL_STUDENT_DETAILS = "FILL_STUDENT_DETAILS";
export const FILL_EMPLOYER_DETAILS = "FILL_EMPLOYER_DETAILS";
export const FILL_BOTH_DETAILS =  "FILL_BOTH_DETAILS";
export const FILL_OTHER_STUDENT_DETAILS = "FILL_OTHER_STUDENT_DETAILS";